---
ID: "000b8e52-2206-4aab-99d0-5c15be06a654"
Parent: "c9f7b808-0821-44ee-91e8-bea5e0353bd6"
Template: "c9f7b808-0821-44ee-91e8-bea5e0353bd6"
Path: /sitecore/templates/Project/MyTenant/Partial Design/__Standard Values
DB: master
SharedFields:
- ID: "55faae90-3bba-4f7f-96fe-13c3f40055ff"
  Hint: Signature
  Value: "__standard-values"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{BCFC7537-EFF4-434C-96F5-BF4F55FD175B}" />
      <d
        id="{0B4A31C9-712D-4578-A396-2DDC0F34B63A}"
        l="{72C595AD-68BB-44BC-B5CD-2A857039515F}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190812T102220Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
