---
ID: "308951b4-a1bf-4308-beba-a9fcfa316d21"
Parent: "906a2ff8-3131-4ba7-a368-044d822098d6"
Template: "9c514ff0-fbf7-42f1-82f6-156272f70caa"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/Storefront/Language Configuration
DB: master
BranchID: "cab95775-02c2-4b53-9cd4-983a8cc5ca4a"
SharedFields:
- ID: "03265dc1-ccfe-470d-aed1-ea9aab5b3f55"
  Hint: Language Set
  Value: "{B8DAEA0F-299B-429A-9133-684BF7CDD924}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 500
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{0D906962-4A82-4462-A680-83AB427FAAFF}"
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Language Configuration
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190809T131457Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
