---
ID: "1a21bd95-dcfe-406d-91b4-004bae006978"
Parent: "906a2ff8-3131-4ba7-a368-044d822098d6"
Template: "9bb44636-1bd5-410c-86cb-b53663944cc3"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/Storefront/Storefront Configuration
DB: master
BranchID: "cab95775-02c2-4b53-9cd4-983a8cc5ca4a"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 250
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{BE2D0F3D-9D02-4C9E-825E-C1C75573834C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190809T131456Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
