---
ID: "6aceba44-4ad9-4e11-842e-f987f191014b"
Parent: "b1768519-ea6b-4801-8dfe-5871f479bd1a"
Template: "b1768519-ea6b-4801-8dfe-5871f479bd1a"
Path: /sitecore/templates/Project/MyTenant/Site/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {E8E8C94F-4248-43C3-A79F-99FBB49D78E6}
    {9F9DFF9E-7011-4809-B28B-ADEFBA3719B4}
    {5ECD34F4-B36F-4533-9643-DF41CD8B5036}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190808T121420Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
